### ISSUE TITLE
Add component in HACS

### ISSUE THREAD

**Issue by robsonke** [hellqvio86/home_assistant_casambi#1]
Soon I'm in a new house where Casambi lights are installed, so can't wait to start testing your component and help with development if required. Nevertheless, did you consider putting this component in HACS to make installation and updating easy for users? I could do the work if you want to too.

**Comment by hellqvio86** [comment]
I have considered it, its still early day, gui configuration is not supported, etc.

But I am happy to accept PRs :)

**Comment by robsonke** [comment]
I'll create a PR, I think it's just a matter of adding a hacs.json and a info.md. You don't need gui config, just use the existing config yaml.

**Comment by robsonke** [comment]
Could you maybe release 0.0.2? Then HACS will pickup this release with the matching structure.

**Comment by hellqvio86** [comment]
Thanks, just released a new version and it works fine. Made the instructions for HACS a bit more clear as well
