### ISSUE TITLE
Problems with future releases

### ISSUE THREAD

**Issue by rk1959** [hellqvio86/home_assistant_casambi#109]
Hello,
When starting HA the Log contains the folloing lines:

Detected that custom integration 'casambi' calls async_forward_entry_setup for integration, casambi with title: Casambi and entry_id: 01JBXV700DMS4493HV8MK9SGTY, which is deprecated, await async_forward_entry_setups instead at custom_components/casambi/__init__.py, line 57: hass.async_create_task(. This will stop working in Home Assistant 2025.6, please create a bug report at https://github.com/hellqvio86/home_assistant_casambi/issues
Detected that custom integration 'casambi' calls async_forward_entry_setup for integration, casambi with title: Casambi and entry_id: 01JBXV700DMS4493HV8MK9SGTY, which is deprecated, await async_forward_entry_setups instead at custom_components/casambi/__init__.py, line 60: hass.async_create_task(. This will stop working in Home Assistant 2025.6, please create a bug report at https://github.com/hellqvio86/home_assistant_casambi/issues
Detected that custom integration 'hon' calls async_forward_entry_setup for integration, hon with title: ruk1959@gmail.com and entry_id: 01JCBER24FTB1C249VABBHKPN3, which is deprecated, await async_forward_entry_setups instead at custom_components/hon/__init__.py, line 57: hass.async_create_task(. This will stop working in Home Assistant 2025.6, please create a bug report at https://github.com/Andre0512/hon/issues
Detected that custom integration 'hon' calls async_write_ha_state from a thread other than the event loop, which may cause Home Assistant to crash or data to corrupt. For more information, see https://developers.home-assistant.io/docs/asyncio_thread_safety/#async_write_ha_state at custom_components/hon/sensor.py, line 849: self.async_write_ha_state(). Please report it to the author of the 'hon' custom integration

Whats to do

Best regards Rainer

**Comment by hellqvio86** [comment]
Duplicate, issue is already reported in https://github.com/hellqvio86/home_assistant_casambi/issues/108
