### ISSUE TITLE
Connected to casambi but couldn't log in

### ISSUE THREAD

**Issue by nicoshaps** [hellqvio86/home_assistant_casambi#13]
Hi,

I'm trying to setup Casambi on Hass.io. HACS is installed and Casambi component is also installed

I configured all parameter in HA but I'm getting these 2 errors at boot

2021-03-26 21:32:22 ERROR (MainThread) [custom_components.casambi.light] Connected to casambi but couldn't log in
2021-03-26 21:32:17 INFO (MainThread) [homeassistant.components.light] Setting up light.casambi

I tried my credentials via https://developer.casambi.com/console

HTTP RequestPOST https://door.casambi.com/v1/networks/session
Path ParametersNone
Request Body
{
    "email": "name@address.com",
    "password": "password"
}

This is working just fine so I'm wondering why it's not working via the Addon

I tried to capture the trafic via tcpdump on my Router but not seeing the request (TLS)

Also tried to extend the debug via Loger but I'm not getting more details

Is there any option to do the troubleshooting?

Thank you

**Comment by nicoshaps** [comment]
Hi,

I found that I'm not able to login to POST https://door.casambi.com/v1/**users**/session

While login to POST https://door.casambi.com/v1/**networks**/session is ok

Do you think that it could be adapter for Hass.io ?

**Comment by hellqvio86** [comment]
Hi,
Are you using site user credentials for  https://door.casambi.com/v1/**users**/session?

The addon is using both (network session & user session), but as you pointed out we could probably go with either or :)

I need to do some testing on my end, I usually use my library for testing https://github.com/hellqvio86/casambi, I don't do MITM attack or MITM proxy.

**Comment by nicoshaps** [comment]
Hi,

I'm not sure which credentials is needed for Users session

I've a password to access mu network but that's it. I've some users defined in the App but none of these users are able to authenticate

When trying via the WebAPI I'm only able to login via https://door.casambi.com/v1/networks/session
All tests via https://door.casambi.com/v1/users/session are failing.

Can you help me to create a user and run the test again ?

Thank you

**Comment by hellqvio86** [comment]
Its the same credentials as you are using in your Casambi app, the documentation for creating a site:
https://support.casambi.com/support/solutions/articles/12000041325-how-to-create-a-site

I am doing some testing on using only user or network session.

**Comment by nicoshaps** [comment]
Thank you I will run the test

Site feature were disabled in my installation. I will try to create a site & a user

**Comment by nicoshaps** [comment]
Hi

Just to confirm that everything is working after defining a site :)

Do you plan to also allow the change of color on top on the dimmer ? I've these 2 options in the App but not via HA

Thank you for the great work !

**Comment by hellqvio86** [comment]
Great that it worked (closing the issue)!

No I don't have any plan to add that support my self, I don't have any Casambi hardware currently that supports changing colors, but I am happy to accept PR:s

And the python library and Home assistant integration don't  support colors, that's why you don't have the option in Home Assistant. Its not probably that hard to add the support, probably some format joggling, like the brightness support 

Best regards Olof Hellqvist
