### ISSUE TITLE
Color temperature control

### ISSUE THREAD

**Issue by nils-hde** [hellqvio86/home_assistant_casambi#18]
Correct me if I'm wrong, but the Casambi API supports setting the color temperature directly in Kelvin.

So it would be great if one could also set the temperature directly in Home Assistant. This feature is also currently implemented in the Homebridge Add-on for Casambi https://www.npmjs.com/package/homebridge-casambi

**Comment by hellqvio86** [comment]
I got hardware donated to me, so this is something that I will look into

**Comment by hellqvio86** [comment]
Its now supported in v0.40 🙂

**Comment by nils-hde** [comment]
Great! I saw there was a couple of updates in HACS today. We can now use the Occhio light with Adaptive Lighting, thank you 😊
