### ISSUE TITLE
Error: unit_id=1 - value - Dimmer is missing in controls: {}

### ISSUE THREAD

**Issue by Juice10** [hellqvio86/home_assistant_casambi#34]
I'm getting the following error in my home assistant logs:
```
Logger: aiocasambi.unit
Source: /usr/local/lib/python3.9/site-packages/aiocasambi/unit.py:67
First occurred: 17:16:47 (10 occurrences) 
Last logged: 17:21:19

unit_id=1 - value - Dimmer is missing in controls: {}
unit_id=2 - value - Dimmer is missing in controls: {}
```

I have the following entities which are picked up by home_assistant_casambi:
<img width="470" alt="image" src="https://user-images.githubusercontent.com/4106/139462836-8b8ed643-1aa9-405e-9901-a3854321eb0b.png">
<img width="465" alt="image" src="https://user-images.githubusercontent.com/4106/139462895-e42a9935-0009-47cd-84ee-3b287cf20721.png">
The latter is actually a four way (EnOcean) wall switch which looks like it is seen as a light

**Comment by hellqvio86** [comment]
The device id two is reported as offline: 
`2021-10-29 19:26:22 DEBUG (MainThread) [aiocasambi.controller] get_network_state response: {'dimLevel': 0.0, 'activeScenes': [], 'id': 'uDmwUPTjvnYhxFKRbmoJL20QM9DPdZKb', 'revision': 21, 'grade': 'EVOLUTION', 'address': '8d9ab1343dc0', 'name': 'NETWORKNAME', 'type': 'CLOSED', 'timezone': 'Europe/Amsterdam', 'gateway': {'name': 'YOGA TABLET'}, 'units': {'1': {'priority': 0, 'on': False, 'online': False, 'condition': 0, 'status': 'ok', 'activeSceneId': 0, 'controls': [[{'name': 'dimmer0', 'type': 'Dimmer', 'value': 0.0}]], 'dimLevel': 0.0, 'id': 1, 'address': 'e6e205491e8e', 'name': 'Flos ceiling light', 'firmwareVersion': '33.0', 'position': 0, 'fixtureId': 90, 'groupId': 0, 'type': 'Luminaire'}, '2': {'priority': 0, 'on': False, 'online': False, 'condition': 0, 'status': 'ok', 'activeSceneId': 0, 'controls': [[]], 'id': 2, 'address': 'e2150002fc52', 'name': 'Flos wall switch', 'position': 1, 'fixtureId': 200001, 'groupId': 0, 'type': 'BatterySwitch'}}, 'photos': [], 'scenes': {}, 'groups': {}}`

What the library (aiocasambi) looks for is the controls, here is example of a dimable light:
` 'controls': [[{'name': 'overheat', 'type': 'Overheat', 'status': 'ok'}, {'name': 'dimmer0', 'type': 'Dimmer', 'value': 0.0}]]`

Its the same thing with color:
`'controls': [[{'type': 'Dimmer', 'value': 0.0},
                        {'level': 0.49736842105263157,
                            'max': 6000,
                            'min': 2200,
                            'type': 'CCT',
                            'value': 4090.0}]],`

Or rgb:
`'controls': [[{'name': 'dimmer0', 'type': 'Dimmer', 'value': 0.0},
                        {'hue': 0.9882697947214076,
                            'name': 'rgb',
                            'rgb': 'rgb(255, 21, 40)',
                            'sat': 0.9176470588235294,
                            'type': 'Color'},
                        {'name': 'white', 'type': 'White', 'value': 0.0}]],`

That is expected by the aiocasambi and never seen for the switch,  

Controls are either pulled through get_network_state  or sent to aiocasambi and grabbed through process_unit_event.

Can you run the tests in https://github.com/hellqvio86/casambi or https://github.com/hellqvio86/aiocasambi so we can figure out how switches works through the cloud api?

**Comment by Juice10** [comment]
> Can you run the tests in https://github.com/hellqvio86/casambi or https://github.com/hellqvio86/aiocasambi so we can figure out how switches works through the cloud api? 

I'd be more than happy to!
Here is the output from https://github.com/hellqvio86/casambi test.sh:

```
main: config: {'api_key': '[apikey]', 'email': '[email]', 'network_password': '[password]', 'user_password': '[password]', 'unit_id': 2, 'units': [2]}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): door.casambi.com:443
DEBUG:urllib3.connectionpool:https://door.casambi.com:443 "POST /v1/users/session/ HTTP/1.1" 200 683
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): door.casambi.com:443
DEBUG:urllib3.connectionpool:https://door.casambi.com:443 "POST /v1/networks/session/ HTTP/1.1" 200 293
DEBUG:casambi:ws_open response: {'address': 'e6e205491e8e', 'controls': [{'name': 'dimmer0', 'type': 'Dimmer', 'value': 0.0}], 'method': 'unitChanged', 'fixtureId': 90, 'condition': 0.0, 'wire': 1, 'activeSceneId': 0, 'sensors': {}, 'name': 'Flos ceiling light', 'online': False, 'id': 1, 'dimLevel': 0.0, 'on': False, 'status': 'ok'}
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): door.casambi.com:443
DEBUG:urllib3.connectionpool:https://door.casambi.com:443 "GET /v1/fixtures/2 HTTP/1.1" 200 218
DEBUG:casambi:get_fixture_information: headers: {'X-Casambi-Key': '[apikey]', 'X-Casambi-Session': '[session]', 'Content-type': 'application/json'} response: {'id': 2, 'type': 'Luminaire', 'vendor': 'Casambi', 'model': 'Board', 'isLuminaire': True, 'isSwitch': False, 'isLightSensor': False, 'isPresenceSensor': False, 'translations': {}, 'controls': [{'type': 'dimmer', 'id': 0, 'readonly': False}]}
Unit fixture information for unit: 2
{'controls': [{'id': 0, 'readonly': False, 'type': 'dimmer'}],
 'id': 2,
 'isLightSensor': False,
 'isLuminaire': True,
 'isPresenceSensor': False,
 'isSwitch': False,
 'model': 'Board',
 'translations': {},
 'type': 'Luminaire',
 'vendor': 'Casambi'}

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): door.casambi.com:443
DEBUG:urllib3.connectionpool:https://door.casambi.com:443 "GET /v1/networks/uDmwUPTjvnYhxFKRbmoJL20QM9DPdZKb/units/2/state HTTP/1.1" 200 227
DEBUG:casambi:get_unit_state: headers: {'X-Casambi-Key': '[apikey]', 'X-Casambi-Session': '[session]', 'Content-type': 'application/json'} response: {'priority': 0, 'on': False, 'online': False, 'condition': 0, 'status': 'ok', 'activeSceneId': 0, 'controls': [[]], 'id': 2, 'address': 'e2150002fc52', 'name': 'Flos wall switch', 'position': 1, 'fixtureId': 200001, 'groupId': 0, 'type': 'BatterySwitch'}
Unit state for unit_id: 2
{'activeSceneId': 0,
 'address': 'e2150002fc52',
 'condition': 0,
 'controls': [[]],
 'fixtureId': 200001,
 'groupId': 0,
 'id': 2,
 'name': 'Flos wall switch',
 'on': False,
 'online': False,
 'position': 1,
 'priority': 0,
 'status': 'ok',
 'type': 'BatterySwitch'}

DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): door.casambi.com:443
DEBUG:urllib3.connectionpool:https://door.casambi.com:443 "GET /v1/networks/uDmwUPTjvnYhxFKRbmoJL20QM9DPdZKb/units/2/state HTTP/1.1" 200 227
DEBUG:casambi:get_unit_state: headers: {'X-Casambi-Key': '[apikey]', 'X-Casambi-Session': '[session]', 'Content-type': 'application/json'} response: {'priority': 0, 'on': False, 'online': False, 'condition': 0, 'status': 'ok', 'activeSceneId': 0, 'controls': [[]], 'id': 2, 'address': 'e2150002fc52', 'name': 'Flos wall switch', 'position': 1, 'fixtureId': 200001, 'groupId': 0, 'type': 'BatterySwitch'}
Does unit support color temperature: False
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): door.casambi.com:443
DEBUG:urllib3.connectionpool:https://door.casambi.com:443 "GET /v1/networks/uDmwUPTjvnYhxFKRbmoJL20QM9DPdZKb/units/2/state HTTP/1.1" 200 227
DEBUG:casambi:get_unit_state: headers: {'X-Casambi-Key': '[apikey]', 'X-Casambi-Session': '[session]', 'Content-type': 'application/json'} response: {'priority': 0, 'on': False, 'online': False, 'condition': 0, 'status': 'ok', 'activeSceneId': 0, 'controls': [[]], 'id': 2, 'address': 'e2150002fc52', 'name': 'Flos wall switch', 'position': 1, 'fixtureId': 200001, 'groupId': 0, 'type': 'BatterySwitch'}
Does unit support rgb: False
Turn unit: 2 on!
```

**Comment by hellqvio86** [comment]
Did the unit turn on? 🙂

**Comment by hellqvio86** [comment]
And does the unit turn off work? If those two functions doesn't work then casambi uses different json messages for turning on off switches. Hopefully it's the same and the only difference is that a switch lacks controls

**Comment by Juice10** [comment]
It’s a battery-less kinetically powered wall (rocker) switch. It doesn’t turn on/off, so it idled for a long time while the test script tried to turn it on.

**Comment by hellqvio86** [comment]
Bad news then, the json message for turning it on / off is different, so the library that is doing the heavy lifting doesn't know how to communicate with the switch through the cloudapi.

I have upgraded the integration and changed the error message to a debug message (still need it in the debug log for development). But you should not be spammed with errors now. Lipstick on the pig, but I probably need hardware in order to implement support for it then.

**Comment by hellqvio86** [comment]
In aiocasambis test function you get feedback from the cloud api, they are sending responses to the calls over the same websocket, so that makes it easier to iterate and test different json messages. It's an asyncio-based library doe, so that's something to keep in mind (makes debugging harder imo).

**Comment by Juice10** [comment]
I've just updated the package in home assistant and error has disappeared! Thanks for that!

**Comment by hellqvio86** [comment]
The error message is now a debug message, switches are not supported yet by aiocasambi, probably need hardware in order to implement that. Happy to accept PRs if someone else want to implement the support.
