### ISSUE TITLE
Core repo missing

### ISSUE THREAD

**Issue by bbuitb** [hellqvio86/home_assistant_casambi#4]
Repository not loading.
20-11-24 19:11:11 ERROR (MainThread) [supervisor.utils.json] Can't read json from /data/addons/git/06a1a366/repository.json: [Errno 2] No such file or directory: '/data/addons/git/06a1a366/repository.json'
20-11-24 19:11:11 ERROR (MainThread) [supervisor.store] https://github.com/hellqvio86/home_assistant_casambi is not a valid add-on repository.

Repository for HA supervisor

**Comment by hellqvio86** [comment]
Hi, 

Its a HACS addon, you can see the way to install it in the readme.

Best Regards Olof Hellqvist
