### ISSUE TITLE
Question: How are HA and the Lights connected?

### ISSUE THREAD

**Issue by CFenner** [hellqvio86/home_assistant_casambi#43]
As I understood the lights do communicate with the Casambi App via the Bluetooth of the device (phone). 

How is HA communicating with the lights? Is it required to have the phone near by? Is the HA host acting as a gateway which needs to be in Bluetooth range? My lights will be in the 2nd floor and HA in the basement. I fear that the connection range is too far away.

**Comment by hellqvio86** [comment]
Its connected through Casambis cloud api.

Casambi light -> Phone running casambi -> Casambi cloud -> Home Assistant

**Comment by hellqvio86** [comment]
So what you need is to place an iOS or android device close to the lights and connect that to the Internet.

HA will use the rest api (pull) and websocket (push) when it interacts with the lights.

The problem you have is that you can't control your lights with HA if something happens to your Internet connection or Casambis servers
