### ISSUE TITLE
Add support for 4 Channel Casambi devices

### ISSUE THREAD

**Issue by SmartMrcl** [hellqvio86/home_assistant_casambi#52]
Hi,

I just installed this integration to connect my huge Casambi network with Home Assistant and it's working fine immediately without any issues. Great project, thanks for making it public! In my Casambi network I’m using several 4 channel dimmer/fixtures for controlling 4 different LED Strips or areas in the room. Unfortunately you didn't integrate the support for this fixtures/model/light so far. Currently I'm just able to switch and dim the 4 channels simultaneously by home assistant, I can't control them independent.

Can you add the support of Casambi 4Ch(Dim/Dim/Dim/Dim) fixtures?
I can tell you a reference Casambi fixture ID if that’s helpful.

Thanks for your support,
Marcel

**Comment by hellqvio86** [comment]
Hi,
I need references hardware in order to add support.

But I am willing to accept PRs.

**Comment by hellqvio86** [comment]
Other users have similar lights, think they lights are 2 channels, anyway one user implemented support for `Distribution/Vertical`and a service  `casambi.light_turn_on service`. Try that service out and see if you can turn on individual channels through it :slightly_smiling_face: 

The integration will show each specific unit right now, so a 1 <-> 1 relationship, if its a light that is

**Comment by SmartMrcl** [comment]
Thanks for your fast reply.
I will search for the conversations about Distribution/Vertical.

There are a lot of hardware who could participate of this additional support.
I don't know how familiar you are with Casambi "Profiles".
There are a lot of 4 channel dimmers and LED drivers running Casambi on the market.
The CBU-PWM4 is probably the most popular one. On this model you can set different "Profiles" using the casambi App. If I set a RGB or RGBW Profile in the App, I can already control this dimmer using your integration. If I set a Profile to control all 4 channels independently, it's not working. 
Do you have RGBW device in your Casambi Network? If you tell me which hardware you have in hand I can check if it can also be set to 4CH Dim for testing porpoise.

I know a lot of Casambi and have good connections to Casambi, but I just started working with HA and Github.

**Comment by hellqvio86** [comment]
I am not at all familiar with Casambi profiles. I have a bunch of LD220WCM_onoff and two test devices who users have donated to me, a dimmable light and a RGB light strip. 

So RGB and RGBW support is implemented and should work.

**Comment by SmartMrcl** [comment]
Yes RGB is working fine.
Can you tell me the name of the Casambi device controlling the RGB Light Strip?
Maybe I can check whether it can also be changed to 4CH dim for testing porpoise.
If not, I can also check if I can donate a suitable device.

But there is also an alternative way to solve my issue.
As you know it's possible to create scenes in the Casambi App and I know it's possible to switch these scenes using the API.
Is there a way to integrate this scenes in HA?

**Comment by hellqvio86** [comment]
The Casambi device that controls the RGB Light Strip is a *CBU-PWM4*.

But please test out *Distribution/Verticaland* attribute in *casambi.light_turn_on* services. The user who implemented that has a Casambi unit with two built in leds, so its probably the same thing in the Casambi api.

**Comment by hellqvio86** [comment]
Have you had time testing controlling the 4 channels through **Distribution/Vertical** setting in the **casambi.light_turn_on** service?

**Comment by weinberger** [comment]
Hello @hellqvio86, 

I am not sure if this is the right place but I have issues with Distribution/vertical setting. My lights definitely support it but if try to use it by the service nothing happened. Can I provide any additional information?

**Comment by hellqvio86** [comment]
> Hello @hellqvio86, 
> 
> I am not sure if this is the right place but I have issues with Distribution/vertical setting. My lights definitely support it but if try to use it by the service nothing happened. Can I provide any additional information?

Hi,
Please open another issue and provide debug logs, I don't own a device that supports distribution/vertical setting but I might be able to help if I am given some debug logs to go on.

**Comment by hellqvio86** [comment]
Closing the issue because of inactivity
