### ISSUE TITLE
Support Screens / Shutters in Home Assitant (Casambi)

### ISSUE THREAD

**Issue by nicoshaps** [hellqvio86/home_assistant_casambi#60]
Is there any chance to support Up and Down screens via Home Assistant and Casambi?

In my Casambi App I don’t have the option to chose the final position it’s just a button Up or Down (see picture). I tried to use them as a light in HA but there is no movement when changing the status

![image](https://user-images.githubusercontent.com/81387288/203288710-d36b9205-b8bf-4156-9c93-962505786368.png)

As an alternative I can use the native Casambi App

I don't have developpement skills but will be happy to support you to test or capture any usefull information

**Comment by hellqvio86** [comment]
Casambi is not supporting this in its api: 

```

Thank you for contacting Casambi support.

​

​If the feature is not mentioned in our developer documentation, then it's unfortunately not supported. ​The API only offers "limited" functions for lighting control.

​

Apologies for the inconvenience.

```

Please create a feature request to casambi, api in question that the integration uses: https://developer.casambi.com/
