### ISSUE TITLE
End of API beta phase

### ISSUE THREAD

**Issue by CFenner** [hellqvio86/home_assistant_casambi#65]
I just asked to expend the validity of my API key and got this response:

>Thanks for contacting Casambi support.
​
>Your Casambi API-key is/was already set to be valid until the current end of the Beta fase, which is 31st of May 2023.

Any idea what happens after the end of the beta?

**Comment by CFenner** [comment]
​
> There Casambi API-key will likely become a paid service after the beta phase. For this we don't have any details yet, but customers with an existing beta API-key will likely be informed regarding the matter closer to the end of the beta phase.

**Comment by hellqvio86** [comment]
No idea, I have only been hearing that they are moving to a payed plan, I hope they still have a free starter plan for small deployments. I for instance it not interested in paying a plan to pay for having a phone connected to a cloud api.

If that's the case I will probably move to casambi-bt, the library didn't work last time I checked it out. But it looks like it started going again (more project activity). 

So I hope they keep it free of charge for personal use 🙂

**Comment by hellqvio86** [comment]
It has also been discussed in this project: https://github.com/awahlig/homebridge-casambi/issues/9 , but they have been quite about the different tiers (if any that is).

**Comment by triumfas** [comment]
I hope they will stick to: https://casambi.com/wp-content/uploads/2020/04/casambi-cloud-API-online.pdf
Small scale use is free.
Data access fee for wider
production deployments.

**Comment by hellqvio86** [comment]
Thanks for the slide deck, hope they keep to what they are saying, a pay wall would definitely be a deal breaker for me 🙂

**Comment by Superkikim** [comment]
They told me that at plan end of Beta, I'll have to ask again for a key. Most probably, it won't be ready in May anyway. So... And indeed, should be free for small deployment. Let's hope.

**Comment by Kopernikus1979** [comment]
Same here, asked for key and got: 

```
Dear Nico,

Thank you for contacting Casambi support.

I'm sorry to say that our API service is in the BETA phase, which means we have granted limited access to new features that we are currently developing and testing. We will not be onboarding new test-phase users for the time being, unfortunately. 

Apologies for any inconvenience.
```

**Comment by Kopernikus1979** [comment]
Got an update:

`•	The current end of the beta phase is 31st of May 2023, when the beta will either be extended (along with likely more users), or then we'll release the full version of the API-key - which will likely be a paid service.`

So no Casambi for me.... I only have 2 Casambi devices built-in to a Winsol solar screen, so maybe I will see the replace the Casambi driver with a Zigbee or other driver....

**Comment by hellqvio86** [comment]
I don't think that many home users will pay for a cloud api.

I suggest to checkout: https://github.com/lkempf/casambi-bt

They are working on local Bluetooth control, if they get going the casambi devices don't have to go to ewaste.

**Comment by hellqvio86** [comment]
Closing issue, what I have seen is that the api keys is only for companies
