### ISSUE TITLE
Init assertion error in case of disabled entities

### ISSUE THREAD

**Issue by robsonke** [hellqvio86/home_assistant_casambi#7]
Creating a new ticket as a followup of #3 since I still face the assertion error:
```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/aiocasambi/websocket.py", line 137, in running
    self.session_handler_callback(SIGNAL_DATA)
  File "/usr/local/lib/python3.8/site-packages/aiocasambi/controller.py", line 228, in session_handler
    self.callback(SIGNAL_DATA, new_items)
  File "/config/custom_components/casambi/light.py", line 162, in signalling_callback
    self.units[key].process_update(value)
  File "/config/custom_components/casambi/light.py", line 236, in process_update
    self.async_schedule_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 438, in async_schedule_update_ha_state
    assert self.hass is not None
AssertionError
```

I did some more digging, the assertion error is thrown by the last line in the stacktrace by hass code itself:
```
@callback
    def async_schedule_update_ha_state(self, force_refresh: bool = False) -> None:
        """Schedule an update ha state change task.

        This method must be run in the event loop.
        Scheduling the update avoids executor deadlocks.

        Entity state and attributes are read when the update ha state change
        task is executed.
        If state is changed more than once before the ha state change task has
        been executed, the intermediate state transitions will be missed.
        """
        if force_refresh:
            assert self.hass is not None
            self.hass.async_create_task(self.async_update_ha_state(force_refresh))
        else:
            self.async_write_ha_state()
```

I noticed the same kind of problem here: https://github.com/StyraHem/ShellyForHASS/issues/341

I'm running on the latest Hassio version. Searched more and stumbled upon https://github.com/JoDehli/PyLoxone/issues/39 and that seems to be the reason. I have one disabled entity (because it doesn't exist). I now enabled it again and my integration works again!

Sorry for the track record above but then you have all info. I think we should catch the possible existence of disabled entities too to make it more resilient.

**Comment by hellqvio86** [comment]
Great report, I think I know where the problem lies in the source code, we are scheduling a refresh even doe its disabled, I will look into it when I have time :)

**Comment by hellqvio86** [comment]
I have done some testing in a feature branch and it's probably just checking if the entity is enabled, but doesn't work that well when enabling/disabling entitys.

That need to be addressed:
https://developers.home-assistant.io/docs/entity_registry_disabled_by/

https://developers.home-assistant.io/docs/device_registry_index

**Comment by hellqvio86** [comment]
So the code that is causing this exception if the unit is disabled is probably this:
```
def set_online(self, online):
        self.unit.online = online

        _LOGGER.debug(f"set_online to {online} for unit {self}")

        self.async_schedule_update_ha_state(True)
```
**self.async_schedule_update_ha_state(True)** at the end.

**Comment by hellqvio86** [comment]
I have released a new version which should work better with disabled entries when reconnecting **v0.17**. But entity registry needs to be looked into, so the addon follow the right flow when disabling/enabling entities.

**Comment by robsonke** [comment]
Nice, I'll give it a try and test it with an entity disabled.

**Comment by robsonke** [comment]
Confirmed, it works with disabled entities now too! The reconnect seems to work well too, since my internet connection is one big drama but the websocket auto reconnects.

**Comment by hellqvio86** [comment]
Great! :-)

The timeouts between each connection is 5 minutes, you can set a custom time now in the config:

```
light:
  platform: casambi
  ...
  network_timeout: 30    #default is 300 seconds
```

**Comment by hellqvio86** [comment]
Closing this issue then, I will look into the Home Assistant registry when time permits.
