### ISSUE TITLE
Match units by their address and not by index

### ISSUE THREAD

**Issue by CFenner** [hellqvio86/home_assistant_casambi#78]
**Is your feature request related to a problem? Please describe.**

I recently removed and readded two units again. In HA they showed up as new lights due to the id being `networkId-unitIndex` (?). So the newly added light have id `..-4` and `..-5`.

**Describe the solution you'd like**

It would be nice to use the address of a unit combined with the network id instead.

**Describe alternatives you've considered**

**Additional context**

**Comment by hellqvio86** [comment]
Good point, I started a branch for it: https://github.com/hellqvio86/home_assistant_casambi/pull/79, https://github.com/hellqvio86/aiocasambi/pull/20

It seems to work in aiocasambi, but that code base needs some work...

**Comment by hellqvio86** [comment]
The mac address is now used in master :slightly_smiling_face:

**Comment by CFenner** [comment]
Nice, thanks.

**Comment by CFenner** [comment]
<img width="662" alt="Bildschirm­foto 2022-11-29 um 08 51 52" src="https://user-images.githubusercontent.com/9592452/204470315-8eaa48fa-37c7-4a1a-a6b6-16a2a0e352bb.png">

So now I have another set of light due to the changed IDs. I guess we need to implement a way to remove the old one's. Otherwise reconfiguring the integration solves this.
