### ISSUE TITLE
Casambi powered shades

### ISSUE THREAD

**Issue by Superkikim** [hellqvio86/home_assistant_casambi#89]
I have a set of Winsol shades, as well as a Winsol Pergola. Winsol chose Casambi to operate their shades and leds. 

Currently, Shades are working great with your latest integration version however they are recognized as lights rather than covers. 

Fixtures are:

Fixture ID: 21899
Fixture mode: EXT/1ch/DIM
Model:  SO!V4
Vendor: LEDsGo

Any chance to get these implemented as covers ?

**Comment by hellqvio86** [comment]
Please provide debug logs, they should not be detected as lights, so thats probably a bug, depending on what the api is saying.

And bad news regarding your shades, this is the answer I got today regarding screens/shutters:
```
Thank you for contacting Casambi support.

​

​If the feature is not mentioned in our developer documentation, then it's unfortunately not supported. ​The API only offers "limited" functions for lighting control.

​

Apologies for the inconvenience.
```

So you need to ask them to support it.


And I have the same answer to this as https://github.com/hellqvio86/home_assistant_casambi/issues/88 , I will not develop support for devices that I don't have physical access to, that say others might we willing to do that.

**Comment by hellqvio86** [comment]
Closing this issue since Casambi isn't supporting the use case through the cloud api which this integration is based on.
