### ISSUE TITLE
Connected to casambi but couldn't log in

### ISSUE THREAD

**Issue by smartechru** [hellqvio86/home_assistant_casambi#9]
Hello @hellqvio86,

Thanks for a great job!
I followed the instructions in README and got the error `Connected to casambi but couldn't log in`.
In `secrets.yaml` file, I added these fields:
```
casambi_email: <my email>
casambi_api_key: <api key>
casambi_network_password: <net pwd>
casambi_user_password: <user pwd>
```
In `configurations.yaml` file, I added the following fields:
```
# Lights
light:
  # Casambi
  - platform: casambi
    email: !secret casambi_email
    api_key: !secret casambi_api_key
    network_password : !secret casambi_network_password # The network password
    user_password : !secret casambi_user_password # The site password for your user
    network_timeout: 30    # default is 300 seconds
```
Could you please let me know what the issue is? Thanks in advance!

**Comment by hellqvio86** [comment]
Hi,
Can you share your logs (please remove passwords)? It seems like you have followed the instructions 🙂

You can also test the credentials with the aiocasambli libraries. I will add an example yaml config for the test.sh script

**Comment by hellqvio86** [comment]
Can you change the debug level to DEBUG or try the aiocasambi library out? You might need to speak to the casambi support team.

The login process is the same for both my aiocasambi library and casambi library, the last is not as cluttered but the plugin uses the async casambi library

**Comment by smartechru** [comment]
Okay, I will try the aiocasambi library.

**Comment by smartechru** [comment]
Hi @hellqvio86 
I've tried the aiocasambi library and tested it as you mentioned in the README file.
Of course, I've put the casambi login detail and API key in the `casambi.yaml` file.
```
python -m src.aiocasambi.__main__
2021-01-29 04:58:33,984 90068 MainProcess __main__ get_casambi_controller WARNING  Connected to casambi but couldn't log in
2021-01-29 04:58:33,984 90068 MainProcess __main__ main     ERROR    Couldn't connect to Casambi controller
```
It still gives me the same error. Please advise me if you have any solution. Thanks in advance.

**Comment by hellqvio86** [comment]
Your credentials are wrong, please run the following (adapt it depending on your environment):
`sudo pip3 install casambi`
`python3`
 ```
  api_key = 'REPLACEME'
  email = 'replaceme@replace.com'
  network_password = 'REPLACEME'
  user_password = 'REPLACEME'

  worker = casambi.Casambi(api_key=api_key, email=email, \
    user_password=user_password, network_password=network_password)
  worker.create_user_session()
  worker.create_network_session()
  worker.ws_open()

  print("Turn unit on!")
  worker.turn_unit_on(unit_id=1)
  time.sleep(60)

  print("Turn unit off!")
  worker.turn_unit_off(unit_id=1)
  time.sleep(60)

  units = worker.get_unit_list()

  print("units: {}".format(units))

  scenes = worker.get_scenes_list()

  worker.ws_close()
```
  
  If a error happens before _ws_open()_, you need to talk directly to casambi support (support@casambi.com), something is then either wrong with your casambi api account or with your credentials, I can sadly not help then.

**Comment by smartechru** [comment]
Thanks for your note, @hellqvio86 
I will definitely contact them.

**Comment by smartechru** [comment]
There was a typo when putting the password. It seems to work!
Thanks @hellqvio86

**Comment by hellqvio86** [comment]
Great, that you got it working 🙂
