### ISSUE TITLE
Status code 429  - Qouta limits exceeded

### ISSUE THREAD

**Issue by hellqvio86** [hellqvio86/home_assistant_casambi#91]
I have started to see a lot of status code 429: "Quota limits exceeded" recently. I have asked Casambis support about it.

**Comment by CFenner** [comment]
Maybe there has been a change on Casambi side in preparation for #65 and the integration is making too many calls for running without a paid api key?

**Comment by hellqvio86** [comment]
It can be all of the reasons, but I think it might be that you are only allowed to have one active websocket on the standard plan. Since I only see it when I try to setup a websocket. 

I hope Casambi can clarify what it is.

**Comment by hellqvio86** [comment]
I don't think its the number of web requests, I am just speculating so I might be wrong, but I implemented a lookup for fixture id and aiocasambi will also only lookup one fixture_id ones and that didn't help. I think its a limit on the number of websockets.

New code is in main/master, I probably not do another release until this is resolved.

**Comment by hellqvio86** [comment]
It's not an user limit, from the support:

> "The "Too many active websocket connections" is not a customer-specific limit in question, and we are working on getting this limitation high enough so that it won't be an issue in the near future."

After out 16th of December server downtime, which has been communicated to our direct customers - the limits will be the following:

​

"Casambi server is going down for a planned maintenance break on Friday, 16th at 13:00 EET (UTC+2, Finland). The estimated end time for the break is Friday, December 16th at 18:00 EET (UTC+2, Finland). The estimated duration of the break is 5 hours.

Notice of a possible impact to Casambi API users after the maintenance break:

New runtime limitations will be introduced for the use of Casambi WebSocket Service. These limitations are intended to prevent excessive usage of the service beyond the following recommendation: "Recommended way to use OPEN message is to create one wire per one network." The implemented limitations are:

- Maximum number of open wires per network per WebSocket: 1 
    
- Maximum total number of wires per network across all WebSocket connections: 20"
