### ISSUE TITLE
Can´t get integration to start

### ISSUE THREAD

**Issue by UlfOdesjo** [hellqvio86/home_assistant_casambi#94]
Hi
I´ve installed the last version of the integration through HACS
Great job BTW :-) Thanks!

Obviously Casambi has started to hand out API keys again, because I got one the other week.
Site is set up and gateway is present through an iPad.

I can´t find anywere in the documentation were I should enter my credentials and API key

I found a note in a forum about it and put it in configuration.yaml like this
# Light
light:
  # Casambi
  - platform: casambi
    email: xxxxx
    api_key: xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx
    network_password: xxxxxxxxxxxxxx # The network password
    user_password: xxxxxxxxxxxxx # The site password for your user

However then I got a warning that it´s deprecated to put it in configuration.yaml.
Where should i put it?

**Expected behavior**

Nothing happens! Can´t find any lights anywhere

**Debug logs**

This is found in the log

2023-04-19 20:50:06.093 WARNING (MainThread) [custom_components.casambi.light] Using Casambi integration through configuration.yaml is deprecated, please consider to switch to configuration flow!

2023-04-19 20:50:06.109 ERROR (MainThread) [homeassistant.components.light] Error while setting up casambi platform for light
Logger: homeassistant.components.light
Source: custom_components/casambi/light.py:94
Integration: Light ([documentation](https://www.home-assistant.io/integrations/light), [issues](https://github.com/home-assistant/home-assistant/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+light%22))
First occurred: 8:50:06 PM (1 occurrences)
Last logged: 8:50:06 PM

Error while setting up casambi platform for light
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 304, in _async_setup_platform
    await asyncio.shield(task)
  File "/config/custom_components/casambi/light.py", line 94, in async_setup_platform
    config = hass.data[DOMAIN][config_entry.entry_id]
AttributeError: 'NodeDictClass' object has no attribute 'entry_id'
```

```

**Platform information (please complete the following information):**

Home Assistant 2023.4.5
Supervisor 2023.04.0
Operating System 10.0
Frontend 20230411.1 - latest

Running on a RPI3

**Comment by hellqvio86** [comment]
You have to set it up through the gui, under setup integration. But if you are running the new firmware (not legacy) I would advise you to use the casambi-bt integration. Then you don't need casambi gateway or api key.

Sadly that integration do not support legacy firmware, the one I have to run. But if you can run the new firmware, go for that. You then have less components that can break and it's less dependent on Internet/Cloud 🙂

**Comment by UlfOdesjo** [comment]
Thanks for your swift response.
The issue is I cant find any integration setup in the gui. Where should I look?

When installing the instruction is:
Installation via HACS (recommended)
Setup HACS https://hacs.xyz/
HACS -> Integrations -> + -> Casambi -> Install

However, there is no Install, only Download
![image](https://user-images.githubusercontent.com/42774489/233284415-89f331d9-6141-4cac-a023-fab6917bf675.png)
![image](https://user-images.githubusercontent.com/42774489/233284590-dd92369b-95c2-4c09-b340-fded70336c9e.png)
![image](https://user-images.githubusercontent.com/42774489/233284750-f0bcaebb-fa1b-4f95-9ab6-c24a7c0fb567.png)


Fot the casambi-bt integration I guees I need BT capabilities in my HA computer or how should it otherwise work without the gateway?

**Comment by hellqvio86** [comment]
You have installed it then :slightly_smiling_face: 

What you need to do is:
1.  To restart home assistant (you have installed a custom plugin).
2. Go to Settings -> "Devices & Services" -> Add integration -> casambi 
3. Follow the setup flow.

But I would really advise you to go with https://github.com/lkempf/casambi-bt-hass if you don't run the legacy firmware, then you don't need a phone tablet on 24/7 and it will probably be more stable. 

You don't have to pay for the api either, Casambi are changing cost model and its unclear if the api will remain free.

Probably better to pay for a cheap bluetooth dongle https://www.home-assistant.io/integrations/bluetooth/ .

But Raspberry Pi 3 Model B have builtin support for bluetooth low energy. Of course you can run this integration, but I would advice against it if you can get the other addon running, less moving parts and it is less dependent on the cloud to work :slightly_smiling_face:

**Comment by UlfOdesjo** [comment]
Awesome. Now it works, thanks :-)

I´ll absolutely look into the casambi-bt integration.
